### ISSUE TITLE
Upstart session support

### ISSUE THREAD

**Issue by CameronNemo** [eworm-de/netlink-notify#1]
Would you be open to a patch that added an Upstart session job to go alongside the systemd service?

**Comment by eworm-de** [comment]
Upstart is pretty dead these days, no? Do you still use it?

**Comment by CameronNemo** [comment]
It is still used as a session init on ubuntu xenial, which is supported until 2021.

**Comment by eworm-de** [comment]
Ah, the LTS release. Well, if it helps you... As we expect systemd to be the default these days - please do not install with default target.
